### ISSUE TITLE
Pretty print code

### ISSUE THREAD

**Issue by mogsdad** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#110]
[DavidG](http://chat.stackoverflow.com/transcript/message/28105512#28105512) brought this up in chat.

See [How can we avoid “overhang” code indentation?](http://meta.stackoverflow.com/questions/304072)

Since the general message from that meta post is that automatic reformatting is difficult and bad, Magic Editor should not make magical changes to code. (Yay! Done that part already.)

However, providing the ability to farm out reformatting to a web service, under user control, might be really handy.

And DavidG wants a button. Maybe two or three. Make them big and shiny.

**Comment by Tiny-Giant** [comment]
Yeah, that's do-able. And I would like it as well. I'm going to hardcode it for spaces instead of tabs.

**Comment by mogsdad** [comment]
Migrated to [new repository #43](https://github.com/SO-Close-Vote-Reviewers/UserScripts/issues/43).
