### ISSUE TITLE
Leading spaces removed when first line is code

### ISSUE THREAD

**Issue by mogsdad** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#13]
If a post begins with a code block that starts with 4-space indents, the leading spaces are removed from the first line.

Further, this does not appear in the diff preview.

**Comment by mogsdad** [comment]
Also happens with lists, e.g. [this post](http://stackoverflow.com/a/33007829/1677912) in its original form.

**Comment by Tiny-Giant** [comment]
Hrmmm, this must have something to do with the omission, I'll look into this deeper.
