### ISSUE TITLE
Replacements with dots get improperly capitalized

### ISSUE THREAD

**Issue by mogsdad** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#17]
Words containing periods to start with are OK, but those that have periods added by RegExp rules are affected.

Example: nodejs gets changed to Node.js by RegExp. THEN it gets changed to Node.Js probably by the firstcaps rule.

```
        nodejs: {
            expr: /\bnode.?js/gi,
            replacement: "Node.js",
            reason: "trademark capitalization"
        },
```

**Comment by mogsdad** [comment]
See also e.g., i.e. - Not cool!

**Comment by mogsdad** [comment]
Another [example post](http://stackoverflow.com/questions/33109136/linkage-error-for-adding-pd4ml-using-maven), where `*.xml` became '*.Xml'.

**Comment by mogsdad** [comment]
Mostly fixed, but not completely, with 1.5.2.30. Node.js is left alone, great. And i.e. survives, yay.

But `*.xml` now becomes `*.XML`. It's a different cause for the problem, I think. Now it seems that file name patterns aren't being recognized as immutable.

**Comment by Tiny-Giant** [comment]
Yeah, because it is so hard to differentiate between filenames and thing names, file names don't get left out. What this means is that the acronym capitalization rules will need a `(!?\.)` before the acronym.

**Comment by mogsdad** [comment]
The code we forked had already dealt with this, sans documentation of course. Acronym RegExes already had ([^\b\w.]|^) as their lead-in, but then needed to return that as $1. Noisy code, but it worked.

https://regex101.com/r/kF1oQ7/1

**Comment by mogsdad** [comment]
Interesting. If using `String.toUpperCase` to capitalize an entire acronym, there is no need to track the lead-in capture group!
