### ISSUE TITLE
Spaces are removed before link references

### ISSUE THREAD

**Issue by mogsdad** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#2]
Markup link references normally have a couple of leading spaces:

```
  [1]: http://example.com/this_is_a_reference
^^
```

Observed in [1.5.2.9](https://github.com/Tiny-Giant/Stack-Exchange-Editor-Toolkit/commit/45006f068cd79faaeb4b8c47098c9ca8839bf66a#diff-d2d08e4fa6134f3ba409bec1ddd3e970).

**Comment by mogsdad** [comment]
Probably due to spacesbeforesymbols which doesn't respect spaces at the start of lines:

            spacesbeforesymbols: {
                expr: /\s+([.,!?;:])(?!\w)/g,
                replacement: "$1",
                reason: "punctuation & spacing"
            },

**Comment by Tiny-Giant** [comment]
This shouldn't be affected because link blocks are omitted, I'll look into this deeper.

**Comment by mogsdad** [comment]
No longer an issue, tested with 1.5.2.29.
