### ISSUE TITLE
Windows sucks

### ISSUE THREAD

**Issue by mogsdad** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#65]
More to the point, the RegExp for windows is over-zealous, modifying every instance of "win".

```
win-win
```

becomes

```
Windows-Windows 
```

See https://regex101.com/r/jF9zK1/7, which illustrates the problem.

**Comment by Tiny-Giant** [comment]
Windows is horrible. https://regex101.com/r/jF9zK1/8

**Comment by mogsdad** [comment]
cement? cool.
