### ISSUE TITLE
<b> </b> can cause crash

### ISSUE THREAD

**Issue by mogsdad** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#66]
Observed on [this post](http://stackoverflow.com/questions/14455434/iis-7-5-special-characters-in-url-rewrite-external-file).

```
but if I put some non standard alphanumeric character it will crahs (e.g.) old<b>ò</b>site
```

Running on this post will cause a crash, with error:

> ```
> TypeError: replace is undefined
> ```

here:

```
                if(literal) return '<code>' + replace.replace(/</g,'&lt;').replace(/(?:^`|`$)/g,'') + '</code>';
```

The unicode character had nothing to do with it. Changing the html tags to markdown avoids the crash.

**Comment by Tiny-Giant** [comment]
If I ever figure out how to reproduce this in a safe environment...

**Comment by Tiny-Giant** [comment]
Underscores, always the underscores.
