### ISSUE TITLE
I feel lucky!

### ISSUE THREAD

**Issue by mogsdad** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#78]
Kinda like google search, we could have an "I feel lucky" button that would auto-edit AND submit with one click. Useful for races to edit all-caps, for example.

**Comment by Tiny-Giant** [comment]
Sounds good, should be pretty easy to implement.

**Comment by mogsdad** [comment]
Maybe it's time for new icons while we're at it?

http://fortawesome.github.io/Font-Awesome/icon/pencil-square-o/

https://fortawesome.github.io/Font-Awesome/icon/magic

**Comment by rjrudman** [comment]
I'd be wary of this one - don't want to get into a situation where bad edits are being made because the edits made by this script aren't sanity checked.

**Comment by Tiny-Giant** [comment]
That is a valid point.

**Comment by mogsdad** [comment]
@rjrudman I understand the sentiment - it would just be too tempting. While there's no guarantee that the user _will_ look at the diff carefully and make a complete and valid ("sane") edit, we don't need to bypass the step.
