### ISSUE TITLE
Indent / Outdent code

### ISSUE THREAD

**Issue by mogsdad** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#92]
For proper layout in lists, it's necessary to indent code cod by multiples of 4 spaces.

Example post: The original version of [this question](http://stackoverflow.com/questions/34276347/register-service-provider-in-laravel).

---
1. Code Service Provider:
   
   class EloquentEventServiceProvider extends ServiceProvider
   {
       public function boot()
       {}
   
   ```
   public function register()
   {
       $this->app->bind('app\\Repositories\\EventRepository', 'app\\Repositories\\Eloquent\\EventEloquentRepository');
   }
   ```
   
   }

---

The code here has been indented 4 spaces by use of the "code" button in the default editor, however it needs to be indented 8 characters because it's within a numbered list.

It would be nice if EditMagic<sup>TM</sup> let us select the code block and click a button to shift it right 4 more spaces.

**Comment by Tiny-Giant** [comment]
It should be pretty easy to do this in the diff, I'll take a look and see what I can come up with.

**Comment by mogsdad** [comment]
My email is my SO id at gmail.

**Comment by mogsdad** [comment]
Migrated to new [repository #40](https://github.com/SO-Close-Vote-Reviewers/UserScripts/issues/40).
