### ISSUE TITLE
Auto changes the file name

### ISSUE THREAD

**Issue by K-Guan** [Tiny-Giant/Stack-Exchange-Editor-Toolkit#93]
Sometimes if the post is looks like:

```
<other text>

script.py:
<other text>

main.py
<other text>
```

The editor will auto change the file name from `script.py` to `Script.py` and change `main.py` to `Main.py`. 

Am image about this issue:

![issue example](http://i.stack.imgur.com/8yudI.png)

**Comment by Tiny-Giant** [comment]
Will look into it. Thanks for the bug report.

**Comment by mogsdad** [comment]
[This](http://stackoverflow.com/questions/34303826/flask-application-not-recognising-dynamically-created-directory) is the post Kevin included a picture of.
